FROM node:14
LABEL maintainer="Maximilian Heuwes <m.heuwes@fz-juelich.de>"

# Set packages from deb.debian.com to archive.debian.com
COPY ./config/buster-sources.list /etc/apt/sources.list
RUN apt-get update && \
    apt-get install -y wget && \
    wget -O /tmp/debian-keyring.deb http://http.us.debian.org/debian/pool/main/d/debian-archive-keyring/debian-archive-keyring_2025.1_all.deb && \
    dpkg -i /tmp/debian-keyring.deb && \
    rm /tmp/debian-keyring.deb

RUN apt-get update && \
    apt-get install -y --no-install-recommends ca-certificates curl net-tools procps python-numpy \
                                               python-pip python-pyquery python-setuptools python-wheel tar && \
    rm -rf /var/lib/apt/lists/* && \
    pip install future requests && \
    mkdir /usr/local/kvm-html5/

COPY kvm-html5/package*.json /usr/local/kvm-html5/

RUN cd /usr/local/kvm-html5/ && \
    npm install

COPY kvm-html5/ /usr/local/kvm-html5/

COPY get_java_viewer.py /usr/local/bin/get_java_viewer

WORKDIR /root/

EXPOSE 8080

ENTRYPOINT ["node", "/usr/local/kvm-html5/main.js"]
